export const industry = [
  'BI-отчеты',
  'Гос. заказ',
  'Энергетика',
  'Образование',
  'Финтех',
  'Образ жизни',
  'Медицина',
  'E-commerce',
  'Безопасность',
  'Развлечения',
  'Картография',
];
export const platform = [
  'Android',
  'Chat-system',
  'Telegram',
  'Backend',
  'Windows',
  'Панель управления',
  'Web',
  'iOS',
];
export const services = [
  'Релиз',
  'Сопровождение',
  'Дизайн',
  'Тестирование',
  'Разработка',
  'Предпроектная деятельность',
  'Аналитика',
  'Приемка',
];
export const langs = [
  'Node.JS',
  'Java',
  'Xamarin',
  'Wordpress',
  'Drupal 8, Angular',
  'ASP.NET Core, Azure',
  'MS Power BI',
  '1C-Битрикс',
  'Objective-C',
  'C#, UWP',
  'Python',
  'PHP',
  'Kotlin',
  'MODX',
  'Swift',
  'PhoneGap',
  'React',
  'Java, Kotlin',
  'Cordova',
  'C++',
];
